### ISSUE TITLE
dogs don't attack creeper in defend mode

### ISSUE THREAD

**Issue by AndreDriesel** [HeroGamers/MyDog#111] opened 2024-01-31 07:15 UTC
### Type of bug

Other unexpected behaviour

### Bug description

When setting all dogs into defend mode /mydog defend all, than they will attack every mob/player with does damage to player as well as the target the player attacks himself.
This is working fine will all mobs instead of creepers, They only get attacked in aggressive mode.

### Steps to reproduce

Have 1 or more dogs
do /md defend all
attack a creeper

### Expected behaviour

I have expected that they will attack creeper

### Actual behaviour

Ignore creepers

**Comment by HeroGamers** [comment] 2024-03-08 15:12
The defend mode is basically the "Minecraft default" mode - which means that wolves will not attack creepers.

The attack mode, however, looks for mobs nearby actively, and selects them as targets for the dogs.

Hence, I will close this as a duplicate of #66 .

**Closed by HeroGamers** 2024-03-08 15:12 UTC
Labels: bug
