### ISSUE TITLE
Command all puppies at once

### ISSUE THREAD

**Issue by excaliburkim** [HeroGamers/MyDog#71] opened 2022-12-28 00:06 UTC
Command all puppies at once
- Everyone sit down!
- Everyone stand up!
- Everyone, come here!
- Everyone hide! (Processing so that it is not visible on the screen)

**Comment by HeroGamers** [comment] 2022-12-28 11:28
Duplicate of #51 

The “duplicate” issue is only for the comehere command, but the same thing can be applied for all commands, that’s a very good idea!
I will merge the issues.

**Closed by HeroGamers** 2022-12-28 11:28 UTC
