### ISSUE TITLE
If you transfer a dog via Greifprevention plugin (/givepet), the dog doesn't transfer owners in the MyDogs side

### ISSUE THREAD

**Issue by MCHalfAssed** [HeroGamers/MyDog#62] opened 2022-11-13 16:05 UTC
If you transfer a dog via Greifprevention plugin (/givepet), the dog doesn't transfer owners in the MyDogs side. When the player who owns the dog logs out, the dog teleports to the original MyDogs owner, but you can't interact with it.

**Comment by HeroGamers** [comment] 2022-11-15 00:06
Hi there,
This is not a bug in MyDog, so to speak, but more of a feature suggestion, since I can see that GriefPrevention just changes the owner of the pet (https://github.com/TechFortress/GriefPrevention/blob/master/src/main/java/me/ryanhamshire/GriefPrevention/PlayerEventHandler.java#L1202).

I will however see if it is feasible to put up a sort of event in order to monitor whether the owner of a Tameable changes, such that the dog can be reassigned to another player.

**Comment by HeroGamers** [comment] 2023-05-29 01:26
Please use MyDog's transfer/trade system instead of GriefPrevention's givepet, as it would otherwise require GriefPrevention to hook into MyDog's API and check if a dog is owned by MyDog first (which I don't think they will implement).

**Closed by HeroGamers** 2023-05-29 01:26 UTC
Labels: enhancement
