### ISSUE TITLE
Trying to revive dead dogs with no economy provider

### ISSUE THREAD

**Issue by Ryebloom** [HeroGamers/MyDog#78] opened 2023-02-07 02:35 UTC
One of my players dogs died and we tried to get it back. It's asking for money but we have no plugin related to that? is there one we should install or a way to turn that off

**Comment by HeroGamers** [comment] 2023-02-08 07:44
You should be able to set the `RevivalPricePerLevel` option to 0.

**Comment by Ryebloom** [comment] 2023-02-08 20:06
Thank you for the response. I've done that and it shows up as 0 in game but whenever i or anyone else tries to revive a dog we get the message of "an internal error has occurred while attempting to perform this command".  Do you know why this ir or how i can fix it?

**Comment by HeroGamers** [comment] 2023-02-10 06:51
I will look into it, it's probably a bug with the economy - and either way it shouldn't try to withdraw anything if no economy provider was found, or if the amount is below or equal to 0.

**Comment by NomadBal** [comment] 2023-04-21 07:35
Same thing is happening to me. Maybe add a toggle to let dogs be revived using regular XP?

**Comment by HeroGamers** [comment] 2023-04-22 14:38
> Same thing is happening to me. Maybe add a toggle to let dogs be revived using regular XP?

This feature got requested here: https://github.com/HeroGamers/MyDog/issues/79

**Comment by HeroGamers** [comment] 2023-05-26 19:47
Duplicate of #61

**Closed by HeroGamers** 2023-05-26 19:47 UTC
Labels: bug
